name: Backend Continuous Integration

on:
  # pull_request: #To run on pull_request to the main brach where there is code change in backend folder.
  #   branches:
  #     - main
  #   paths:
  #     - 'starter/backend/**'
  workflow_dispatch:  # Allows manual execution

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd starter/backend
          pip install pipenv
          pipenv install --dev #Specifically add --dev to install the dev-packages from Pipfile in starter/backend folder.

      - name: Run Linter
        run: |
          cd starter/backend
          pipenv run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd starter/backend
          pip install pipenv
          pipenv install #No need to install dev packages as it using user defined tests.

      - name: Run Tests
        run: |
          cd starter/backend
          pipenv run test

  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .
