name: Backend CD

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'backend/**'
  workflow_dispatch:  # Allows manual execution

env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::352026621605:user/github-action-user
  ECR_REPOSITORY: 352026621605.dkr.ecr.us-east-1.amazonaws.com/backend

jobs:
  build:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd starter/backend
          docker build --tag $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name cluster

      - name: Update Image Tag in Kustomize
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=$ECR_REPOSITORY:${{ github.sha }}
          kustomize build | kubectl apply -f -
