name: Frontend Continuous Deployment

on:
  push: #To run run on push event to the main brach where there is code change in frontend folder.
    branches:
      - main
    paths:
      - 'starter/frontend/**' #Trigger only when there is change in frontend dirctory.
  workflow_dispatch:  # Allows manual execution

  # ECR repository urls are stored as enviroment variables (PROD) along with region and backend url. AWS secrets are also stored in the same PROD env.
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' #Cache action to restore cache before dependency install. This will speed up the workflow execution.
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run ESLint
        run: |
          cd starter/frontend
          npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' #Cache action to restore cache before dependency install. This will speed up the workflow execution.
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run Tests
        run: |
          cd starter/frontend
          CI=true npm test

  build:
    name: Build and Push Frontend Image
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.FRONTEND_ECR_REPOSITORY }}

      - name: Build and Push Docker Image
        run: |
          cd starter/frontend
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ vars.REACT_APP_MOVIE_API_URL }} --tag ${{ vars.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ vars.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    environment: PROD
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name cluster

      - name: Update Image Tag in Kustomize
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=${{ vars.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }}
          kustomize build | kubectl apply -f -
