name: Frontend Continuous Deployment

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'frontend/**'
  workflow_dispatch:  # Allows manual execution

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 352026621605.dkr.ecr.us-east-1.amazonaws.com/frontend
  REACT_APP_MOVIE_API_URL: http://a7519f93feb8240acb88487504c599eb-999897023.us-east-1.elb.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}

      - name: Build and Push Docker Image
        run: |
          cd starter/frontend
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} --tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name cluster

      - name: Update Image Tag in Kustomize
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          kustomize build | kubectl apply -f -
